server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://10.0.3.174:3306/jiankong?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: market
    password: password
    driver-class-name: com.mysql.jdbc.Driver

    thymeleaf:
      cache: false
      prefix: classpath:/templates/
      suffix: .html
      encoding: UTF-8
      content-type: text/html
      mode: HTML5
  resources:
    static-locations: classpath:/
mybatis:
  type-aliases-package: com.pyw.springmybatis.entity
  mapper-locations: classpath:mapping/*Mapper.xml

logging:
  level:
    com:
      pyw:
        springmybatis:
           mapper : debug

# pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
